# Generated by Django 5.0.2 on 2024-04-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0009_rename_event_created_by_event_created_by_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
