# Generated by Django 5.0.2 on 2024-04-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0013_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
