# Generated by Django 5.0.2 on 2024-04-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0014_remove_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ems.location'),
            preserve_default=False,
        ),
    ]
