# Generated by Django 5.0.3 on 2024-04-06 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_alter_event_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_link', models.FileField(upload_to='uploads/')),
                ('link_type', models.CharField(choices=[('PROFILE_PICTURE', 'Profile Picture'), ('EVENT', 'Event')], default='EVENT', max_length=50)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_links', to='event_management.event')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
