# Generated by Django 5.0.2 on 2024-04-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0007_reportevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reports_count',
            field=models.IntegerField(default=0),
        ),
    ]
