# Generated by Django 5.0.2 on 2024-04-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_event_reports_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevent',
            name='reports_count',
            field=models.IntegerField(default=0),
        ),
    ]
